spring:
  config:
    activate:
      on-profile: prod

management:
  endpoints.web.exposure.include: ${MANAGEMENT_EXPOSURE_INCLUDE:health}
  endpoint.health.show-details: never

growth:
  storage:
    endpoint: ${MINIO_ENDPOINT}
    public-endpoint: ${MINIO_PUBLIC_ENDPOINT:${MINIO_ENDPOINT}}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    bucket: ${MINIO_BUCKET}
