# RabbitMQ 配置文件

## 监听地址
listeners.tcp.default = 5672

## 管理插件
management.tcp.port = 15672
management.load_definitions = /etc/rabbitmq/definitions.json

## 日志
log.file.level = info
log.console.level = info

## 内存限流
vm_memory_high_watermark.relative = 0.6

## 磁盘限流
disk_free_limit.absolute = 2GB

## 心跳
heartbeat = 60

## 默认虚拟主机
default_vhost = wuyao

## 消息持久化
queue_master_locator = min-masters
